version: '3.8'

networks:
  nginx_net:
    driver: bridge

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  